[package]
name = "rocket"
version = "0.1.0"
authors = ["Luke O'Malley <luke@lukeomalley.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rocket = "0.5.0-rc.2"